import Link from "next/link";
import { redirect } from "next/navigation";
import { asc } from "drizzle-orm";

import { db, organization } from "@harly/db";
import { getDeploymentBootstrapStatus } from "@harly/auth/setup";

import { SetupClaimForm } from "./SetupClaimForm";

export const dynamic = "force-dynamic";

export default async function SetupPage() {
  const bootstrap = await getDeploymentBootstrapStatus();
  const [existing] = await db
    .select({ slug: organization.slug })
    .from(organization)
    .orderBy(asc(organization.createdAt))
    .limit(1);

  if (existing || bootstrap.completed) {
    redirect("/");
  }

  return (
    <div className="flex min-h-screen flex-col">
      <header className="flex items-center justify-between px-8 py-6">
        <Link href="/" className="font-display text-lg tracking-tight text-pine">
          Harly
        </Link>
        <Link
          href="/login"
          className="text-sm font-medium text-muted-foreground transition hover:text-foreground"
        >
          Sign in
        </Link>
      </header>

      <main className="flex flex-1 flex-col items-center justify-center px-6 pb-20">
        <div className="w-full max-w-sm text-center">
          <div className="mx-auto mb-6 flex size-14 items-center justify-center rounded-2xl bg-primary">
            <span className="font-display text-lg font-bold text-primary-foreground">
              H
            </span>
          </div>

          <h1 className="font-display text-3xl tracking-tight text-foreground">
            Welcome to Harly
          </h1>
          <p className="mt-3 text-sm leading-6 text-muted-foreground">
            Enter the one-time token generated by <code>create-harly init</code>.
            Authorization lasts 15 minutes and is limited to the configured owner email.
          </p>

          <SetupClaimForm />

          <p className="mt-10 text-xs text-muted-foreground">
            Harly — open-source applicant tracking system
          </p>
        </div>
      </main>
    </div>
  );
}
